{{- if .Values.nginx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xcoding.nginx.serviceAccountName" . }}
  labels:
    {{- include "xcoding.nginx.labels" . | nindent 4 }}
  {{- with .Values.nginx.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.nginx.serviceAccount.automount }}
{{- end }}
